### ISSUE TITLE
speedup development by using skaffold file sync

### ISSUE THREAD

**Issue by jlewi** [kubeflow/code-intelligence#78]
PR #77 contains skaffold.yaml files to continuously build and deploy the microservices. 

Skaffold is building the containers on the cluster using Kaniko. The builds look like they are taking O(minutes) to rebuild.

We should be able to speed that up by taking advantage of skaffold's [file sync feature](https://skaffold.dev/docs/pipeline-stages/filesync/) to directly synchronize files to the containers and skipping the container rebuilds.

**Comment by jlewi** [comment]
I gave this a quick try and skaffold gives me the warngin

```
WARN[0772] error adding dirty artifact to changeset: inferring syncmap for image gcr.io/issue-label-bot-dev/bot-worker: SyncMap is not supported by this builder 
```

**Comment by jlewi** [comment]
Using manual mode for skaffold file sync seems to work; Here's my sample stanza

```
    sync:
        manual:
        - src: 'py/code_intelligence/*.py'
          dest: '/'
        - src: 'py/label_microservice/*.py'
          dest: '/'        
```

I was relying on flask's reloader to reload things when the code changed. If instead of using flask we just have a binary running pubsub; we might need to run it in a subprocess and restart it ourselves.

Then again maybe we should continue to use flask to do things like a health check.
